name: fluxify:0.0.1

services:
  pg:
    image: bitnami/postgresql
    container_name: fluxify-pg
    ports:
      - 5433:5432
    env_file:
      - ./server/.env
    volumes:
      - pg-volume:/var/lib/postgresql/data
  
  redis:
    image: redis
    container_name: fluxify-redis
    ports:
      - 6379:6379

volumes:
  pg-volume: